# Generated by Django 2.0.4 on 2018-05-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('CanAdministrate', models.CharField(max_length=300)),
                ('CanAccessUserContent', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=64)),
                ('Apellidos', models.CharField(max_length=300)),
                ('IMG0', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=64)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Ingredientes', models.CharField(max_length=300)),
                ('Instrucciones', models.CharField(max_length=300)),
                ('UserId', models.CharField(max_length=10)),
                ('IMG0', models.CharField(max_length=64)),
                ('IMG1', models.CharField(max_length=64)),
                ('IMG2', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('PrivilegeId', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UCrendential', models.CharField(max_length=64)),
                ('PCrendential', models.CharField(max_length=300)),
                ('Mail', models.CharField(max_length=300)),
                ('IsActive', models.CharField(max_length=300)),
                ('DateCreated', models.CharField(max_length=300)),
            ],
        ),
    ]
