# Generated by Django 2.0.4 on 2018-05-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestingController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Mail',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
    ]
